name: Publish Playwright Test Report

on:
   push:
    branches:
      - main
   schedule:
     - cron: '00 17 * * 1-5' # At 17:00 UTC, Monday to Friday
     
jobs:
  ui_test:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npm run test:dev
      - name: copy contents of playwright-report
        if: always()
        run: |
          mkdir -p generated-report
          cp -r ${{ github.workspace }}/playwright-report/* generated-report/


      # - name: Publish HTML report 
      #   if: always() # We want this to always run, even if tests fail prior to this step running
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ${{ github.workspace }}/playwright-report # This is where index.html will be output
      #     user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
      #     user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
      - name: Publish HTML report
        if: always()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: generated-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
